### PR TITLE
add basic templates and URLs

### PR DESCRIPTION
**Pull request by thatbudakguy**
- adds basic django templates for home, members list, and personography page
- adds snippets for header, footer, personography page tabs
- adds relevant URLs and views for members, assuming a basic list/detail pattern
- adds robots.txt URL and test
- adds a small amount of styles & javascript

### CODE REVIEW

**Comment by thatbudakguy** [comment]
looks like this needs view and URL tests. will return if I have time today

**Comment by rlskoeser** [comment]
@thatbudakguy don't worry about unit tests for the views - we should do those when we implement the user stories for these (even though you've done a lot of the prep work for that already).  I view this work more as prototyping the template and styles.

What kind of feedback would be helpful?

A few comments and questions so far:
* I like how clean and readable the html is.  
* Should we have any documentation about working with semantic-ui? Can we just include it and not need to install anything for development?
* Any thoughts on documentation/guidelines to provide for the team to work within the framework and structure you've set up?
* Any reason you are using CSS rather than SCSS?
* Hadn't thought about putting app-specific styles into the app static folder rather than a site-wide one, but it seems like a nice idea.  (Although I do wonder if we'll always know when styles are app specific?)

I don't object to merging this -- seems like a great starting point for the public-facing functionality -- but I think we probably should wait until the current work has been carved off into a release branch.

**Comment by thatbudakguy** [comment]
update on this PR: will probably revisit to make it integrate more with django forms as I'm currently doing on ppa. leaving alone for now.

**Comment by thatbudakguy** [comment]
update #2: this will need a bunch of changes based on things I learned from PPA. I'm also thinking about compiling a slightly tweaked base semantic UI stylesheet (e.g. with our breakpoints and grid settings) so that I can build using that as an alternative to the totally stock one.

**Pull request closed without merging**
