### PR TITLE
Bugfix/tab navigable hidden menu

### PR DESCRIPTION
**Pull request by rlskoeser**
Set menu to `display: none` as well as `opacity: 1` when it should be hidden, so that it isn't tab navigable when closed.

### CODE REVIEW

**Comment by rlskoeser** [comment]
@thatbudakguy oh, I tested but didn't notice the animation had changed! (Although I did wonder about it a bit.) Yes, that approach sounds fine. Sounds like you have fixes ready to commit?

**Comment by thatbudakguy** [comment]
I've added them, do you want to pull the changes and test as well?

**Comment by rlskoeser** [comment]
@thatbudakguy will do

**Comment by rlskoeser** [comment]
@thatbudakguy your changes didn't fully resolve the problem for me. Does the tabindex need to be set on the individual links and not just the containing div?  Also seems like there's an additional problem: when the menu is active you can keep on tabbing to the page content that you can't see, with the menu still open.

I grabbed this issue because I thought it was an easy fix (based on John's comments), but it seems that it isn't.

**Pull request closed without merging**
