### PR TITLE
Zoom in/out to view larger card image

### PR DESCRIPTION
**Pull request by rlskoeser**

### CODE REVIEW

**Comment by rlskoeser** [comment]
@thatbudakguy thanks for catching the cursor problem! I was applying the style too broadly.

I tried setting the overflow but it didn't have much impact — I guess it would need to be set on the body? Can you think of any way to do that in pure css?

**Comment by thatbudakguy** [comment]
ah, makes sense - I was afraid of that. no way to do it in css that I know of. not a big deal though.

**Comment by rlskoeser** [comment]
@thatbudakguy the scroll doesn't so matter much since I'm linking back to `#` to zoom out, which puts you back at the top of the page (I wasn't sure if there was a better option). 

I've adjusted the cursor styles if you want to review.

**Comment by thatbudakguy** [comment]
I'd say just go ahead and merge it then.

**Pull request merged**
